### ISSUE TITLE
似乎与jjc查拆同时使用会导致mirai/hoshino之一的随机崩溃

### ISSUE THREAD

**Issue by Naexen** [iamwyh2019/aircon#1]
之前一直没有搞明白哪里出了错 禁用aircon之后就没有发生崩溃情况了
具体是命令行界面没有任何反应
由于不太清楚有没有崩溃日志所以只能提交这些
在群里搜索查拆之后返回查询出错 然后这俩就会随机挂一个

**Comment by iamwyh2019** [comment]
好的，我会尝试复现一下。感谢你的反馈
ヾ(❀╹◡╹)ﾉ~

**Comment by iamwyh2019** [comment]
您好。我们暂时无法复现您所说的问题，也没有收到其他类似的反馈。aircon插件不需要联网获取资源，也不会占用其它插件或机器人本体的资源和配置文件，且在后台并不是一直运行，只在触发命令时计算温度并写入自身配置文件，因此不太可能影响其它插件和机器人本体的运行。由于框架和机器人崩溃的原因很多，建议您反映至机器人开发组或开发者社区。再次感谢您的反馈，欢迎您继续提交issue。
